// AUTO-GENERATED — NE PAS MODIFIER MANUELLEMENT
// Genere par scripts/sync-client.ts depuis CLIENT.md
// Pour modifier: editer CLIENT.md puis lancer npm run sync-client

export const clientConfig = {
  NOM_ENTREPRISE: "DG COUVERTURE",
  NOM_LEGAL: "GODICHE DESIRE",
  SIRET: "993 402 130",
  METIER: "couvreur",
  METIER_LABEL: "Couvreur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "DESIRE",
  NOM_DIRIGEANT: "GODICHE",
  DIPLOME_DIRIGEANT: "Artisan couvreur",
  ANNEE_CREATION: "2025",
  ANNEES_EXPERIENCE: "0",
  TELEPHONE: "06 24 76 35 78",
  EMAIL: "contact@dgcouverture.fr",
  ADRESSE: "10 Rue de Faronville",
  CODE_POSTAL: "77310",
  VILLE: "BOISSISE-LE-ROI",
  DEPARTEMENT: "Seine-et-Marne",
  REGION: "Île-de-France",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 8h00-18h00, Sam: 9h00-13h00",
  ZONE_INTERVENTION: "Île-de-France",
  LATITUDE: "48.5217",
  LONGITUDE: "2.4085",
  COULEUR_PRIMAIRE_HUE: "220",
  COULEUR_PRIMAIRE_900: "oklch(0.22 0.06 220)",
  COULEUR_ACCENT_HUE: "25",
  COULEUR_ACCENT_500: "oklch(0.64 0.16 25)",
  COULEUR_FOND_50: "oklch(0.985 0.005 80)",
  FONT_TITRES: "Playfair Display",
  FONT_CORPS: "DM Sans",
  DOMAINE: "www.dgcouverture.fr",
  META_TITLE: "DG COUVERTURE | Couvreur à Boissise-le-Roi",
  META_DESCRIPTION: "Couvreur professionnel à Boissise-le-Roi (77310). Couverture neuve, rénovation de toiture, zinguerie, isolation. Intervention rapide, devis gratuit.",
  META_KEYWORDS: "couvreur, couverture, toiture, Boissise-le-Roi, Seine-et-Marne, Île-de-France, rénovation toiture, zinguerie, isolation toiture, dépannage toiture, couvreur professionnel",
  SCHEMA_TYPE: "RoofingContractor",
  SLOGAN: "Votre Toiture - Notre Passion",
  ACCROCHE_HERO: "Votre Toiture — Entre de Bonnes Mains",
  DESCRIPTION_ENTREPRISE: "DG COUVERTURE est votre artisan couvreur à Boissise-le-Roi, en Seine-et-Marne. Depuis 2025, nous intervenons sur toute l'Île-de-France pour tous vos besoins de couverture : couverture neuve, rénovation, zinguerie, isolation thermique et dépannage d'urgence. Un savoir-faire artisanal au service de votre toiture.",
  DESCRIPTION_FOOTER: "Artisan couvreur professionnel basé à Boissise-le-Roi en Île-de-France. Couverture neuve, rénovation, zinguerie, isolation et dépannage urgent.",
  DESCRIPTION_APROPOS: "Fondée par Désiré Godiche, DG COUVERTURE est née d'une passion profonde pour le métier de couvreur et du désir de proposer un travail de qualité en Île-de-France.",
  SERVICE_1_TITRE: "Couverture Neuve",
  SERVICE_1_DESC: "Installation complete de votre toiture en ardoise, tuile ou zinc, avec une finition soignee et durable.",
  SERVICE_2_TITRE: "Renovation de Toiture",
  SERVICE_2_DESC: "Refection partielle ou totale de votre couverture pour redonner etancheite et esthetique a votre toit.",
  SERVICE_3_TITRE: "Zinguerie",
  SERVICE_3_DESC: "Pose et reparation de gouttieres, descentes EP, cheneaux, noues et abergements en zinc ou cuivre.",
  SERVICE_4_TITRE: "Isolation de Toiture",
  SERVICE_4_DESC: "Isolation thermique par l'interieur ou l'exterieur (sarking) pour ameliorer le confort et reduire la facture energetique.",
  SERVICE_5_TITRE: "Depannage & Urgence",
  SERVICE_5_DESC: "Intervention rapide pour fuites, tuiles cassees, bachage d'urgence et reparations suite a intemperies.",
  SERVICE_6_TITRE: "Demoussage & Entretien",
  SERVICE_6_DESC: "Nettoyage, traitement anti-mousse et hydrofuge pour prolonger la duree de vie de votre toiture.",
  GOOGLE_MAPS_URL: "",
  GOOGLE_REVIEWS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  PINTEREST_URL: "",
  TEMOIGNAGE_1_NOM: "Famille Martin",
  TEMOIGNAGE_1_VILLE: "Boissise-le-Roi",
  TEMOIGNAGE_1_TEXTE: "DG COUVERTURE a effectue une renovation complete de notre toiture en ardoise. Travail impeccable, equipe ponctuelle et professionnelle. Nous recommandons vivement !",
  TEMOIGNAGE_1_NOTE: "5",
  TEMOIGNAGE_2_NOM: "Laurent Dupont",
  TEMOIGNAGE_2_VILLE: "Fontainebleau",
  TEMOIGNAGE_2_TEXTE: "Intervention rapide pour reparer une fuite apres une tempete. Diagnostic precis et reparation efficace. Travail de qualite et devis honnete.",
  TEMOIGNAGE_2_NOTE: "5",
  TEMOIGNAGE_3_NOM: "Marie & Jean Petit",
  TEMOIGNAGE_3_VILLE: "Moret-sur-Loing",
  TEMOIGNAGE_3_TEXTE: "Renovation complete de notre zinguerie avec gouttieres en zinc. Travail soigne, materiel de qualite. Aucun probleme depuis, meme apres les pluies.",
  TEMOIGNAGE_3_NOTE: "5",
  HEBERGEUR_NOM: "Vercel Inc.",
  HEBERGEUR_ADRESSE: "340 Pine Street, Suite 701, San Francisco, CA 94104, USA",
  HEBERGEUR_SITE: "vercel.com",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
  PACK_PHOTOS_METIER: "couvreur",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
